CFLAGS=-Wall -g

# delete all ex... except the .c files
clean:
	find `pwd` -name "ex*" -not -name "*.c" | xargs rm -rf

# list the programs that will be compiled when `make all`
all: ex1-hello ex3-printf ex5-printf ex6-math ex7-arrays-sizeof
